### ISSUE TITLE
Menu hover color

### ISSUE THREAD

**Issue by SvenErikLarsen** [SvenErikLarsen/Telegram-Translation-Night-theme-CSS#1]
I can't find the menu hover color, leaving both hover and text color white.

https://i.imgur.com/YmXPQC3.png

**Comment by Ecron** [comment]
I think I solved it in #2 . Take a look if you please :+1:

**Comment by SvenErikLarsen** [comment]
> I think I solved it in #2 . Take a look if you please 👍

Nice, this looks really good 👌 Thanks!

**Comment by Ecron** [comment]
You're welcome :wink: I'll keep playing with the CSS until I feel it's zen enough :sweat_smile:
